### ISSUE TITLE
http://www.iis.ee.ic.ac.uk/ unreachable？

### ISSUE THREAD

**Issue by Hansry** [vbalnt/tfeat#13]
Hello, I think the website "http://www.iis.ee.ic.ac.uk/" is unreachable, can you post a new website which can offer the .t7 model for me?  Thank you very much!

**Comment by vbalnt** [comment]
Hi, yes I am currently updating the repo, will be ready in a couple of days. 
Will keep this open until it's done

**Comment by vbalnt** [comment]
Hi @Hansry new code is now up, should be much easier to run, since everything is in `pytorch`

**Comment by alebrahim-ali** [comment]
Hi @vbalnt -- sorry to bother you about this again. I'm trying to reach http://www.iis.ee.ic.ac.uk/aleksander.html but the link is not working; like Hansry said before it seems the whole website http://www.iis.ee.ic.ac.uk/ is unreachable.

Do you know how to access http://www.iis.ee.ic.ac.uk/aleksander.html or otherwise contact Professor Aleksander? (https://www.imperial.ac.uk/people/i.aleksander)

I emailed you about this as well. Thank you!
